version: "3" # versão do docker-compose
services: # serviços que precisamos colocar em conteiner
  # e um desses serviços é a nossa aplicação.
  app: # nome da nossa aplicação, pode ser qualquer nome, nesse caso vamos dar o nome de app
    build: 
      context: . # context é o diretório onde a gente está
    # command: "mix phx.server"
    # command: tail -f /dev/null
    tty: true
    ports:
      - '4000:4000'
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME:-sintonia_dev}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASS=${DB_PASS:-postgres}
    volumes:
      - '.:/var/www/html'
    working_dir: /var/www/html
    depends_on:
      - db
    links:
      - db
  db:
    image: 'postgres:10'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-postgres}'
      POSTGRES_DB: '${DB_NAME:-sintonia_dev}'
      POSTGRES_USER: '${DB_USER:-postgres}'
      POSTGRES_PASSWORD: '${DB_PASS:-postgres}'
    volumes:
      - 'main-pgsql:/var/lib/postgresql/data'
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
      retries: 3
      timeout: 5s
volumes:
  main-pgsql:
    driver: local
